version: '3.2'
services:
  bblfsh:
    image: bblfsh/bblfshd:v2.14.0-drivers
    privileged: true
    ports:
      - 9432:9432
    restart: always

  gitcollector:
    image: srcd/gitcollector:v0.0.1-beta.2
    environment:
      GITHUB_ORGANIZATION: ${GITHUB_ORGANIZATION:-}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      LOG_LEVEL: debug
    volumes:
      - type: ${GITBASE_VOLUME_TYPE}
        source: ${GITBASE_VOLUME_SOURCE}
        target: /library
        consistency: delegated

  gitbase:
    #image: srcd/gitbase:v0.21.0-beta1
    image: jfontan/gitbase:siva-2
    ports:
      - 3306:3306
    environment:
      BBLFSH_ENDPOINT: bblfsh:9432
      SIVA: ${GITBASE_SIVA}
    depends_on:
      - bblfsh
    volumes:
      - type: ${GITBASE_VOLUME_TYPE}
        source: ${GITBASE_VOLUME_SOURCE}
        target: /opt/repos
        read_only: true
        consistency: delegated
      - gitbase_indexes:/var/lib/gitbase/index
    restart: always

  bblfsh-web:
    image: bblfsh/web:v0.11.1
    command: -bblfsh-addr bblfsh:9432
    ports:
      - 9999:8080
    depends_on:
      - bblfsh

  redis:
    image: redis:3.2
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  postgres:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  sourced-ui:
    #image: srcd/sourced-ui:v0.3.0-beta.1
    image: srcd/sourced-ui:latest
    restart: unless-stopped
    environment:
      SYNC_MODE: 'true'
      METADATA_DB: metadata
      ADMIN_LOGIN: admin
      ADMIN_FIRST_NAME: admin
      ADMIN_LAST_NAME: admin
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GITBASE_DB: gitbase
      GITBASE_USER: root
      GITBASE_PASSWORD:
      GITBASE_HOST: gitbase
      GITBASE_PORT: 3306
      BBLFSH_WEB_HOST: bblfsh-web
      BBLFSH_WEB_PORT: 8080
      SUPERSET_ENV: production
    ports:
      - 8088:8088
    depends_on:
      - postgres
      - redis
      - gitbase

volumes:
  gitbase_repositories:
    external: false
  gitbase_indexes:
    external: false
  postgres:
    external: false
  redis:
    external: false
